// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: scrapper.proto

package scrapper

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoggingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	EventId       string                 `protobuf:"bytes,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoggingReq) Reset() {
	*x = LoggingReq{}
	mi := &file_scrapper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoggingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoggingReq) ProtoMessage() {}

func (x *LoggingReq) ProtoReflect() protoreflect.Message {
	mi := &file_scrapper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoggingReq.ProtoReflect.Descriptor instead.
func (*LoggingReq) Descriptor() ([]byte, []int) {
	return file_scrapper_proto_rawDescGZIP(), []int{0}
}

func (x *LoggingReq) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LoggingReq) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LoggingReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoggingReq) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *LoggingReq) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type LogRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRes) Reset() {
	*x = LogRes{}
	mi := &file_scrapper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRes) ProtoMessage() {}

func (x *LogRes) ProtoReflect() protoreflect.Message {
	mi := &file_scrapper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRes.ProtoReflect.Descriptor instead.
func (*LogRes) Descriptor() ([]byte, []int) {
	return file_scrapper_proto_rawDescGZIP(), []int{1}
}

func (x *LogRes) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

var File_scrapper_proto protoreflect.FileDescriptor

const file_scrapper_proto_rawDesc = "" +
	"\n" +
	"\x0escrapper.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xa6\x01\n" +
	"\n" +
	"LoggingReq\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x19\n" +
	"\bevent_id\x18\x04 \x01(\tR\aeventId\x123\n" +
	"\bmetadata\x18\x05 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"#\n" +
	"\x06LogRes\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId20\n" +
	"\rLoggerService\x12\x1f\n" +
	"\aSaveLog\x12\v.LoggingReq\x1a\a.LogResB\x13Z\x11scrapper/scrapperb\x06proto3"

var (
	file_scrapper_proto_rawDescOnce sync.Once
	file_scrapper_proto_rawDescData []byte
)

func file_scrapper_proto_rawDescGZIP() []byte {
	file_scrapper_proto_rawDescOnce.Do(func() {
		file_scrapper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scrapper_proto_rawDesc), len(file_scrapper_proto_rawDesc)))
	})
	return file_scrapper_proto_rawDescData
}

var file_scrapper_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_scrapper_proto_goTypes = []any{
	(*LoggingReq)(nil),      // 0: LoggingReq
	(*LogRes)(nil),          // 1: LogRes
	(*structpb.Struct)(nil), // 2: google.protobuf.Struct
}
var file_scrapper_proto_depIdxs = []int32{
	2, // 0: LoggingReq.metadata:type_name -> google.protobuf.Struct
	0, // 1: LoggerService.SaveLog:input_type -> LoggingReq
	1, // 2: LoggerService.SaveLog:output_type -> LogRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_scrapper_proto_init() }
func file_scrapper_proto_init() {
	if File_scrapper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scrapper_proto_rawDesc), len(file_scrapper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scrapper_proto_goTypes,
		DependencyIndexes: file_scrapper_proto_depIdxs,
		MessageInfos:      file_scrapper_proto_msgTypes,
	}.Build()
	File_scrapper_proto = out.File
	file_scrapper_proto_goTypes = nil
	file_scrapper_proto_depIdxs = nil
}
